### ISSUE TITLE
Parallel State execution support

### ISSUE THREAD

**Issue by EvilLord666** [coinbase/step#61]
It is necessary to add support for state machines that contains parallel state.

**Comment by EvilLord666** [comment]
I would like to add that i forked step repo (https://github.com/EvilLord666/step) and added support for Parallel State in my fork. It could be not full support now therefore i am checking it and after i finish it  i would be ready to make PR.

**Comment by grahamjenson** [comment]
Awesome, look forward to the PR, so far the changes are looking really good. Cheers

**Comment by EvilLord666** [comment]
@grahamjenson  I've created pull request (https://github.com/coinbase/step/pull/62)

**Comment by grahamjenson** [comment]
Cheers for the hard work, sorry we did not merge it. We are archiving this now as we are moving this project internal. Cheers again.
